
ALTER TABLE streamers ADD COLUMN kd_ratio REAL DEFAULT 0;
ALTER TABLE streamers ADD COLUMN kda_ratio REAL DEFAULT 0;
ALTER TABLE streamers ADD COLUMN kills INTEGER DEFAULT 0;
ALTER TABLE streamers ADD COLUMN deaths INTEGER DEFAULT 0;
ALTER TABLE streamers ADD COLUMN assists INTEGER DEFAULT 0;
ALTER TABLE streamers ADD COLUMN time_played INTEGER DEFAULT 0;
ALTER TABLE streamers ADD COLUMN total_damage INTEGER DEFAULT 0;
ALTER TABLE streamers ADD COLUMN total_healing INTEGER DEFAULT 0;
